# -*- coding: utf-8 -*-

import json
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator
from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String, Text

from database import Base


class TaskStatus(str, Enum):
    TODO = "todo"
    DOING = "doing"
    DONE = "done"


class TaskPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


def parse_dependency_ids(value: Any) -> list[int]:
    if value in (None, "", []):
        return []

    if isinstance(value, str):
        try:
            value = json.loads(value)
        except json.JSONDecodeError:
            return []

    if isinstance(value, (list, tuple, set)):
        result: list[int] = []
        for item in value:
            try:
                result.append(int(item))
            except (TypeError, ValueError):
                continue
        return result

    return []


def serialize_dependency_ids(value: Any) -> str:
    return json.dumps(parse_dependency_ids(value), ensure_ascii=False)


def task_payload_to_db(payload: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(payload)
    status = normalized.get("status")
    if isinstance(status, TaskStatus):
        normalized["status"] = status.value
    if "dependency_ids" in normalized:
        normalized["dependency_ids"] = serialize_dependency_ids(normalized.get("dependency_ids"))
    return normalized


class TaskBase(BaseModel):
    title: str = Field(..., min_length=1, description="The title of the task")
    description: Optional[str] = Field(None, description="A detailed description of the task")
    status: TaskStatus = Field(default=TaskStatus.TODO, description="The status of the task")
    due_date: Optional[datetime] = Field(None, description="The deadline for the task")
    parent_task_id: Optional[int] = Field(None, description="Parent task ID for task trees")
    dependency_ids: list[int] = Field(default_factory=list, description="Dependent task IDs")
    ai_suggested_priority: Optional[TaskPriority] = Field(None, description="AI suggested priority")
    estimated_hours: Optional[float] = Field(None, ge=0, description="Estimated hours")
    ai_generated: bool = Field(default=False, description="Whether the task is generated by AI")
    execution_notes: Optional[str] = Field(None, description="Experience or execution notes")
    actual_hours: Optional[float] = Field(None, ge=0, description="Actual spent hours")

    @field_validator("title")
    @classmethod
    def title_must_not_be_empty(cls, value: str) -> str:
        if not value or value.strip() == "":
            raise ValueError("Title cannot be empty")
        return value.strip()

    @field_validator("dependency_ids", mode="before")
    @classmethod
    def normalize_dependency_ids(cls, value: Any) -> list[int]:
        return parse_dependency_ids(value)


class TaskCreate(TaskBase):
    pass


class TaskUpdate(BaseModel):
    title: Optional[str] = Field(None, min_length=1, description="The title of the task")
    description: Optional[str] = Field(None, description="A detailed description of the task")
    status: Optional[TaskStatus] = Field(None, description="The status of the task")
    due_date: Optional[datetime] = Field(None, description="The deadline for the task")
    order: Optional[int] = Field(None, ge=1, description="The task display order")
    parent_task_id: Optional[int] = Field(None, description="Parent task ID")
    dependency_ids: Optional[list[int]] = Field(None, description="Dependent task IDs")
    ai_suggested_priority: Optional[TaskPriority] = Field(None, description="AI suggested priority")
    estimated_hours: Optional[float] = Field(None, ge=0, description="Estimated hours")
    ai_generated: Optional[bool] = Field(None, description="Whether the task is generated by AI")
    execution_notes: Optional[str] = Field(None, description="Experience or execution notes")
    actual_hours: Optional[float] = Field(None, ge=0, description="Actual spent hours")

    @field_validator("title", mode="after")
    @classmethod
    def title_must_not_be_empty_on_update(cls, value: Optional[str]) -> Optional[str]:
        if value is not None and value.strip() == "":
            raise ValueError("Title cannot be empty")
        return value.strip() if value is not None else value

    @field_validator("dependency_ids", mode="before")
    @classmethod
    def normalize_dependency_ids(cls, value: Any) -> Optional[list[int]]:
        if value is None:
            return None
        return parse_dependency_ids(value)


class Task(TaskBase):
    id: int
    order: int

    model_config = ConfigDict(from_attributes=True)


class TaskBreakdownRequest(BaseModel):
    goal: str = Field(..., min_length=3, description="The user's high-level goal")
    description: Optional[str] = Field(None, description="Extra context for the goal")

    @field_validator("goal")
    @classmethod
    def goal_must_not_be_empty(cls, value: str) -> str:
        if not value or value.strip() == "":
            raise ValueError("Goal cannot be empty")
        return value.strip()


class RootTaskDraft(BaseModel):
    title: str = Field(..., min_length=1)
    description: Optional[str] = None
    due_date: Optional[datetime] = None


class SubTaskSuggestion(BaseModel):
    title: str = Field(..., min_length=1)
    description: Optional[str] = None
    estimated_hours: Optional[float] = Field(None, ge=0)
    priority: TaskPriority = TaskPriority.MEDIUM
    dependencies: list[int] = Field(default_factory=list, description="1-based dependency indexes")

    @field_validator("title")
    @classmethod
    def subtask_title_not_empty(cls, value: str) -> str:
        if not value or value.strip() == "":
            raise ValueError("Subtask title cannot be empty")
        return value.strip()


class TaskBreakdownResponse(BaseModel):
    root_task_title: str
    summary: str
    suggestions: list[SubTaskSuggestion]
    warnings: list[str] = Field(default_factory=list)


class TaskBreakdownSaveRequest(BaseModel):
    root_task: RootTaskDraft
    subtasks: list[SubTaskSuggestion] = Field(default_factory=list)


class TaskExperience(BaseModel):
    task_id: int
    title: str
    description: Optional[str] = None
    execution_notes: Optional[str] = None
    actual_hours: Optional[float] = None
    similarity_score: float = 0


class TaskDB(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), index=True, nullable=False)
    description = Column(Text, nullable=True)
    status = Column(String(50), default=TaskStatus.TODO.value, nullable=False)
    due_date = Column(DateTime, nullable=True)
    order = Column(Integer, nullable=False, default=0, index=True)
    parent_task_id = Column(Integer, nullable=True, index=True)
    dependency_ids = Column(Text, nullable=True, default="[]")
    ai_suggested_priority = Column(String(50), nullable=True)
    estimated_hours = Column(Float, nullable=True)
    ai_generated = Column(Boolean, nullable=False, default=False)
    execution_notes = Column(Text, nullable=True)
    actual_hours = Column(Float, nullable=True)

    def __repr__(self):
        return (
            f"<Task(id={self.id}, title='{self.title}', order={self.order}, "
            f"status='{self.status}', parent_task_id={self.parent_task_id})>"
        )
